[package]
name = "imtl-sys"
version = "0.1.0"
edition = "2021"

[lib]
name = "imtl_sys"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
rand = "0.8.5"

[build-dependencies]
bindgen = "0.69.1"
pkg-config = "0.3.27"
