name: Centos build

on: [push, pull_request]

env:
  # Customize the env if
  MTL_BUILD_DISABLE_PCAPNG: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/centos/centos:stream8
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        extensions: 'hpp,h,cpp,c,cc'

    - name: Install the build dependency
      run: |
        dnf config-manager --set-enabled powertools
        yum install -y sudo git gcc gcc-c++ meson python3 python3-pip pkg-config json-c-devel libpcap-devel gtest-devel SDL2-devel openssl-devel numactl-devel libasan
        yum install -y dpdk-devel

    - name: Install the python package
      run: pip3 install pyelftools

    - name: Git config
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    #- name: Build dpdk
    #  run: ./script/build_dpdk.sh

    - name: Build
      run: |
        export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/:/usr/local/lib/pkgconfig/
        ./build.sh

    - name: Build with debug
      run: |
        rm build -rf
        export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/:/usr/local/lib/pkgconfig/
        ./build.sh debug