name: FFmpeg plugin build

on:
  push:
    branches:
      - main
      - 'maint-**'
  pull_request:
    branches:
      - main
      - 'maint-**'

env:
  # Customize the env if
  # Disable since mtl patched dpdk pcapng and this job use prebuilt pkg
  MTL_BUILD_DISABLE_PCAPNG: true

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ steps.filter.outputs.ffmpeg_plugin == 'true' }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      
      - uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v2
        id: filter
        with:
          filters: .github/path_filters.yml

  build:
    needs: changes
    if: ${{ github.repository == 'OpenVisualCloud/Media-Transport-Library' && needs.changes.outputs.changed == 'true' }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    container:
      image: ubuntu:latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Update to latest git
        run: |
          apt-get update -y
          apt-get install -y git

      - name: Git config
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: checkout kahawai repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: checkout openh264 repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: 'cisco/openh264'
          path: openh264

      - name: checkout FFmpeg repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: 'FFmpeg/FFmpeg'
          path: FFmpeg

      - name: Install the build dependency
        run: |
          apt-get update -y
          apt-get install -y sudo git gcc meson python3 python3-pip pkg-config libnuma-dev libjson-c-dev libpcap-dev libgtest-dev libsdl2-dev libsdl2-ttf-dev libssl-dev
          apt-get install -y dpdk-dev
          apt-get install -y nasm yasm
          apt-get install -y libavcodec-dev

      - name: Install the python package
        run: pip install pyelftools==0.29 ninja==1.11.1

      - name: Build
        run: |
          ./build.sh

      - name: Build st22 ffmpeg plugin
        run: |
          ./script/build_st22_ffmpeg_plugin.sh

      - name: Build openh264
        run: |
          cd openh264/
          git checkout openh264v2.4.0
          make -j "$(nproc)"
          sudo make install
          sudo ldconfig
          cd ../

      - name: Build ffmpeg 6.1 plugin
        run: |
          cd FFmpeg/
          git checkout release/6.1
          cp -f ../ecosystem/ffmpeg_plugin/mtl_*.c ./libavdevice/
          cp -f ../ecosystem/ffmpeg_plugin/mtl_*.h ./libavdevice/
          git am ../ecosystem/ffmpeg_plugin/6.1/*.patch
          ./configure --enable-shared --disable-static --enable-nonfree --enable-pic --enable-gpl --enable-libopenh264 --enable-encoder=libopenh264 --enable-mtl
          make -j "$(nproc)"
          sudo make install
          sudo ldconfig
          cd ../

      - name: Build ffmpeg 4.4 plugin
        run: |
          cd FFmpeg/
          git checkout release/4.4
          cp -f ../ecosystem/ffmpeg_plugin/mtl_*.c ./libavdevice/
          cp -f ../ecosystem/ffmpeg_plugin/mtl_*.h ./libavdevice/
          git am ../ecosystem/ffmpeg_plugin/4.4/*.patch
          ./configure --enable-shared --disable-static --enable-nonfree --enable-pic --enable-gpl --enable-libopenh264 --enable-encoder=libopenh264 --enable-mtl
          make -j "$(nproc)"
          sudo make install
          sudo ldconfig
          cd ../
